apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: ${{ secrets.AWS_USER_ARN }}
      username: admin_daniel_vu
      groups:
        - system:masters