apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::220923858684:user/admin_daniel_vu
      username: admin_daniel_vu
      groups:
        - system:masters